# Generated by Django 2.2 on 2019-04-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpost',
            name='is_new_thread',
        ),
        migrations.AlterField(
            model_name='mainpost',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
