# Generated by Django 2.2 on 2019-04-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPost', '0002_auto_20190401_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='is_link_post',
            field=models.BooleanField(null=True, verbose_name='Is a Link Post?'),
        ),
    ]
