# Generated by Django 2.2 on 2019-04-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPost', '0003_mainpost_is_link_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='is_link_post',
            field=models.BooleanField(verbose_name='Is a Link Post?'),
        ),
    ]
