# Generated by Django 2.2 on 2019-04-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPost', '0004_auto_20190401_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='votes',
            field=models.ManyToManyField(blank=True, to='Vote.Vote', verbose_name='Votes'),
        ),
    ]
