# Generated by Django 2.2 on 2019-04-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RedditUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('notification', models.ManyToManyField(blank=True, related_name='notification', to='RedditUser.RedditUser', verbose_name='Notification')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='RedditUser.RedditUser', verbose_name='Sender')),
            ],
        ),
    ]
