# Generated by Django 2.2 on 2019-04-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RedditUser', '0001_initial'),
        ('Message', '0002_auto_20190409_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notification',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='RedditUser.RedditUser', verbose_name='Sender'),
            preserve_default=False,
        ),
    ]
