# Generated by Django 2.2 on 2019-04-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], verbose_name='Type'),
        ),
    ]
