# Generated by Django 2.2 on 2019-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0002_auto_20190403_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vote Score'),
        ),
    ]
