# Generated by Django 2.2 on 2019-04-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0003_vote_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='score',
        ),
    ]
