# Generated by Django 2.2 on 2019-04-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0004_remove_vote_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (2, 'Downvote')], verbose_name='Type'),
        ),
    ]
