# Generated by Django 2.2 on 2019-04-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RedditUser', '0001_initial'),
        ('Subreddit', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('is_link_post', models.BooleanField(verbose_name='Is the Post a link?')),
                ('body', models.CharField(blank=True, max_length=500, null=True, verbose_name='Body')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link URL')),
                ('link_preview_img', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Link Preview Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Vote Score')),
                ('downvoters', models.ManyToManyField(blank=True, related_name='downvoters', to='RedditUser.RedditUser', verbose_name='Downvoters')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedditUser.RedditUser', verbose_name='Sender')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subreddit.Subreddit', verbose_name='Subreddit')),
                ('upvoters', models.ManyToManyField(blank=True, related_name='upvoters', to='RedditUser.RedditUser', verbose_name='Upvoters')),
            ],
        ),
    ]
