# Generated by Django 2.2 on 2019-04-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vote', '__first__'),
        ('RedditUser', '0001_initial'),
        ('Subreddit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('is_link_post', models.BooleanField(verbose_name='Is a Link Post?')),
                ('body', models.CharField(blank=True, max_length=500, null=True, verbose_name='Body')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link URL')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedditUser.RedditUser', verbose_name='Sender')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subreddit.Subreddit', verbose_name='Subreddit')),
                ('votes', models.ManyToManyField(blank=True, to='Vote.Vote', verbose_name='Votes')),
            ],
        ),
    ]
