# Generated by Django 2.2 on 2019-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_link_post',
            field=models.BooleanField(verbose_name='Is the Post a link?'),
        ),
    ]
