# Generated by Django 2.2 on 2019-04-08 20:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thread', '0002_auto_20190408_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='link_preview_img',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/jakejohnson/Kenzie/back-end/reddit-clone/media'), upload_to='', verbose_name='Link Preview Image'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
