# Generated by Django 2.2 on 2019-04-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thread', '0002_auto_20190402_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vote Score'),
        ),
    ]
