# Generated by Django 2.2 on 2019-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditUser', '0001_initial'),
        ('Thread', '0004_auto_20190403_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters', to='RedditUser.RedditUser', verbose_name='Downvoters'),
        ),
        migrations.AddField(
            model_name='thread',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to='RedditUser.RedditUser', verbose_name='Upvoters'),
        ),
    ]
