# Generated by Django 2.2 on 2019-04-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thread', '0006_remove_thread_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='score',
        ),
    ]
