# Generated by Django 2.2 on 2019-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thread', '0007_remove_thread_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vote Score'),
        ),
    ]
