# Generated by Django 2.2 on 2019-04-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RedditUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditUserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageReceiverNotification', to='RedditUser.RedditUser', verbose_name='Receiver Notification')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageReceiver', to='RedditUser.RedditUser', verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageSender', to='RedditUser.RedditUser', verbose_name='Sender')),
            ],
        ),
    ]
