# Generated by Django 2.2 on 2019-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditUserMessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditusermessage',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
