# Generated by Django 2.2 on 2019-04-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Thread', '0001_initial'),
        ('RedditUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250, verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Vote Score')),
                ('downvoters', models.ManyToManyField(blank=True, related_name='comment_downvoters', to='RedditUser.RedditUser', verbose_name='Downvoters')),
                ('post_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thread.Thread', verbose_name='Parent Thread')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedditUser.RedditUser', verbose_name='Sender')),
                ('upvoters', models.ManyToManyField(blank=True, related_name='comment_upvoters', to='RedditUser.RedditUser', verbose_name='Upvoters')),
            ],
        ),
    ]
