# Generated by Django 2.2 on 2019-04-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RedditUser', '0001_initial'),
        ('Thread', '0001_initial'),
        ('Vote', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250, verbose_name='body')),
                ('post_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thread.Thread', verbose_name='Parent Thread')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedditUser.RedditUser', verbose_name='Sender')),
                ('votes', models.ManyToManyField(blank=True, to='Vote.Vote', verbose_name='Votes')),
            ],
        ),
    ]
