# Generated by Django 2.2 on 2019-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreadComment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
    ]
