# Generated by Django 2.2 on 2019-04-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreadComment', '0002_threadcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vote Score'),
        ),
    ]
