# Generated by Django 2.2 on 2019-04-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreadComment', '0003_threadcomment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
