# Generated by Django 2.2 on 2019-04-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditUser', '0001_initial'),
        ('ThreadComment', '0004_auto_20190404_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcomment',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='comment_downvoters', to='RedditUser.RedditUser', verbose_name='Downvoters'),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='comment_upvoters', to='RedditUser.RedditUser', verbose_name='Upvoters'),
        ),
    ]
