# Generated by Django 2.2 on 2019-04-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThreadComment', '0005_auto_20190404_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadcomment',
            name='votes',
        ),
    ]
