# Generated by Django 2.2 on 2019-04-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RedditUser', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('sidebar_content', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sidebar Content')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedditUser.RedditUser', verbose_name='Created By')),
                ('moderators', models.ManyToManyField(related_name='moderators', to='RedditUser.RedditUser', verbose_name='Moderators')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to='RedditUser.RedditUser', verbose_name='Subscribers')),
            ],
        ),
    ]
