# Generated by Django 2.2 on 2019-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Message', '0001_initial'),
        ('RedditUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='Message.Message', verbose_name='Messages')),
                ('users', models.ManyToManyField(to='RedditUser.RedditUser', verbose_name='Users')),
            ],
        ),
    ]
