# Generated by Django 2.2 on 2019-04-09 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MessageThread', '0002_auto_20190409_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
