# Generated by Django 2.2 on 2019-04-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subreddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
