# Generated by Django 2.2 on 2019-04-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subreddit', '0002_auto_20190402_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
    ]
